/**
 * ZK Utilities for GridTokenX Privacy
 * 
 * Provides high-level TypeScript wrappers for Ristretto commitments
 * and Zero-Knowledge proofs generated by the WASM module.
 */

import {
    ZkCommitment,
    ZkRangeProof,
    ZkTransferProof,
    loadZkModule,
} from './wasm-bridge';

// The ZK exports ship in the separate lazily-loaded wasm-zk module —
// loadZkModule() handles the one-time init (see lib/wasm-bridge.ts).

export async function createCommitment(value: number, blinding: Uint8Array): Promise<ZkCommitment> {
    const zk = await loadZkModule();
    if (!zk) throw new Error('ZK WASM module not loaded');
    return zk.create_commitment(BigInt(value), blinding);
}

export async function createRangeProof(amount: number, blinding: Uint8Array): Promise<ZkRangeProof> {
    const zk = await loadZkModule();
    if (!zk) throw new Error('ZK WASM module not loaded');
    const proof = zk.create_range_proof(BigInt(amount), blinding);
    return {
        proof_data: Array.from(proof.proof_data),
        commitment: proof.commitment
    };
}

export async function createTransferProof(
    amount: number,
    balance: number,
    senderBlinding: Uint8Array,
    amountBlinding: Uint8Array
): Promise<ZkTransferProof> {
    const zk = await loadZkModule();
    if (!zk) throw new Error('ZK WASM module not loaded');
    const proof = zk.create_transfer_proof(BigInt(amount), BigInt(balance), senderBlinding, amountBlinding);
    return {
        amount_commitment: proof.amount_commitment,
        remaining_commitment: proof.remaining_commitment,
        balance_proof: proof.balance_proof,
        range_proof_data: Array.from(proof.range_proof_data),
    };
}

export async function createUnshieldProof(
    remaining: number,
    blinding: Uint8Array
): Promise<{ commitment: ZkCommitment; range_proof_data: number[] }> {
    const zk = await loadZkModule();
    if (!zk) throw new Error('ZK WASM module not loaded');
    const proof = zk.create_unshield_proof(BigInt(remaining), blinding);
    return {
        commitment: proof.commitment,
        range_proof_data: Array.from(proof.range_proof_data as Uint8Array | number[]),
    };
}

export async function benchmarkProofGeneration(): Promise<{ timeMs: number, rounds: number }> {
    const amount = 500;
    const blinding = window.crypto.getRandomValues(new Uint8Array(32));

    const start = performance.now();
    const rounds = 5;

    for (let i = 0; i < rounds; i++) {
        await createRangeProof(amount, blinding);
    }

    const end = performance.now();
    return {
        timeMs: (end - start) / rounds,
        rounds
    };
}
